### ISSUE TITLE
Compiling v5 Debian 10

### ISSUE THREAD

**Issue by nazcar4** [DriftSolutions/RadioBot#2]
After installing the necessary dev packages and compiling, I find myself in an error in the autodj plugin specifically in the mysql library:
AutoDJ -> Failed in DL_Open (): ./plugins/AutoDJ/adjq_mysql.so: undefined symbol: _ZN8DB_MySQLD1Ev

with which it does not make the queries in the mysql database or add new songs

**Comment by DriftSolutions** [comment]
Ok, try pulling and compiling again.
