### ISSUE TITLE
Usage of Mozilla-tts as a state of the art TTS engine within radiobot (no issue!!!)

### ISSUE THREAD

**Issue by count00zero** [DriftSolutions/RadioBot#4]
I didn't know how to contribute my little TTS workaround, so I opened this issue, which is no issue at all but some sort of feature :)

I always liked radiobot but was also very dissatisfied with the possibilities for TTS on linux (ubuntu).
Since I was very spoiled with the possibilities on windows I couldn't bring myself to using espeak or festival on linux.

After I found mozilla-tts (https://github.com/mozilla/TTS) mainly to use it with liquidsoap (https://github.com/savonet/liquidsoap) I came up with a workaround to use it with radiobot too!

I wrote a wrapper bash (espeak_tts.sh) and placed it within my radiobot path with the following content:

```
#!/bin/bash
text=`cat /opt/radiobot/autodj_script.txt`

#TTS, Mozilla TTS, python libraries, https://github.com/mozilla/TTS
/usr/bin/tts --text "$text" --out_path /opt/radiobot/autodj_script.wav
```
Within the radiobot config (ircbot.conf) I used the possibility to define a custom espeak command:
`eSpeakCommand /opt/radiobot/espeak_tts.sh`

Voila and it works.
Just sharin' :)

**Comment by DriftSolutions** [comment]
Awesome, I added a link to this on the wiki and may add native support in the future for mozilla-tts.
